mode: release+prof
use_in_memory: false
http:
  port: 8080
grpc:
  port: 6345
  hostname: localhost
postgres:
  url: "host=localhost port=5432 user=intern password=fyr8as4da6 dbname=url_db sslmode=disable"
  max_connections: 10
  min_connections: 5
  ttl_idle_connections: 100
logger:
  app_name: "smallurl"
  level: 'warn'
  directory: './app-log/'
  use_std_and_file: true
  allow_show_low_level: false
